CREATE TABLE AMC_CUSTOMER (
  ORG CHAR(12) ,
  CUST_ID BIGINT ,
  ID_NO VARCHAR(30) ,
  ID_TYPE CHAR(1) ,
  TITLE CHAR(1) ,
  NAME VARCHAR(80) ,
  GENDER CHAR(1) ,
  BIRTHDAY DATE ,
  NATIONALITY CHAR(3) ,
  MOBILE_NO VARCHAR(20) ,
  EMAIL VARCHAR(80) ,
  SETUP_DATE DATE ,
  JPA_VERSION INT ,
  LAST_MODIFIED_DATETIME TIMESTAMP ,
  CREATED_DATETIME TIMESTAMP
);

