INSERT INTO `AMC_TABLE_SEQ` (`TABLE_NAME`, `SEQ_VAL`) VALUES ('BIZ_SEQ_NO', '422401');
INSERT INTO `AMC_TABLE_SEQ` (`TABLE_NAME`, `SEQ_VAL`) VALUES ('CONSUMER_SEQ_NO', '839701');
INSERT INTO `AMC_TABLE_SEQ` (`TABLE_NAME`, `SEQ_VAL`) VALUES ('ORDER_LOAN_ID', '306301');
INSERT INTO `AMC_TABLE_SEQ` (`TABLE_NAME`, `SEQ_VAL`) VALUES ('AMC_BATCH_FILE', '306001');
INSERT INTO `AMC_TABLE_SEQ` (`TABLE_NAME`, `SEQ_VAL`) VALUES ('AMC_BATCH_INST_HST', '306001');
INSERT INTO `AMC_TABLE_SEQ` (`TABLE_NAME`, `SEQ_VAL`) VALUES ('AMC_NBS_CUST', '308701');
INSERT INTO `AMC_TABLE_SEQ` (`TABLE_NAME`, `SEQ_VAL`) VALUES ('AMC_ORDER_LOAN', '306901');
INSERT INTO `AMC_TABLE_SEQ` (`TABLE_NAME`, `SEQ_VAL`) VALUES ('YAK_KEY_CONTEXT', '307501');

INSERT INTO `AMC_SYSTEM_STATUS` (`STATUS_ID`, `BUSINESS_DATE`, `PROCESS_DATE`, `LAST_PROCESS_DATE`, `GRACE_TIME`, `MTN_DATE`, `JPA_VERSION`, `AUTO_FLAG`)
VALUES ('1', '1971-03-07', '1971-03-06', '1971-03-05', NOW(), NOW(), '6', '0');