CREATE TABLE AMC_CUSTOMER (
  `ORG` char(12) COLLATE utf8_bin NOT NULL COMMENT '机构号',
  `CUST_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '客户ID',
  `ID_NO` varchar(30) COLLATE utf8_bin NOT NULL COMMENT '证件号码',
  `ID_TYPE` char(1) COLLATE utf8_bin NOT NULL COMMENT '证件类型',
  `TITLE` char(1) COLLATE utf8_bin DEFAULT NULL COMMENT '标题',
  `NAME` varchar(80) COLLATE utf8_bin NOT NULL COMMENT '姓名',
  `GENDER` char(1) COLLATE utf8_bin NOT NULL COMMENT '性别',
  `BIRTHDAY` date NOT NULL COMMENT '出身年月',
  `NATIONALITY` char(3) COLLATE utf8_bin DEFAULT NULL COMMENT '国籍',
  `MOBILE_NO` varchar(20) COLLATE utf8_bin NOT NULL COMMENT '手机号',
  `EMAIL` varchar(80) COLLATE utf8_bin DEFAULT NULL COMMENT '邮箱',
  `SETUP_DATE` date NOT NULL COMMENT '开户时间',
  `JPA_VERSION` int(11) DEFAULT NULL COMMENT '版本',
  `LAST_MODIFIED_DATETIME` timestamp NULL DEFAULT NULL COMMENT '最后修改时间',
  `CREATED_DATETIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`CUST_ID`),
  UNIQUE KEY `IDX_AMC_CUSTOMER_IDNOORGIFTYPE` (`ID_NO`,`ORG`,`ID_TYPE`),
  KEY `IDX_CUSTOMER_MOBILE` (`ORG`,`MOBILE_NO`),
  KEY `IDX_AMC_CUSTOMER_LAST_MODIFY` (`LAST_MODIFIED_DATETIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT '客户信息表';

CREATE TABLE `AMC_ACCOUNT` (
  `ORG` char(12) COLLATE utf8_bin NOT NULL COMMENT '机构号',
  `ACCT_NO` bigint(20) NOT NULL COMMENT '账户编号',
  `ACCT_TYPE` char(1) COLLATE utf8_bin NOT NULL COMMENT '账户类型',
  `CUST_ID` bigint(20) NOT NULL COMMENT '客户编号',
  `CUST_LIMIT_ID` bigint(20) NOT NULL COMMENT '客户额度编号',
  `PRODUCT_CD` char(6) COLLATE utf8_bin NOT NULL COMMENT '产品代码',
  `DEFAULT_LOGICAL_CARD_NO` varchar(19) COLLATE utf8_bin NOT NULL COMMENT '默认逻辑卡号',
  `CURR_CD` char(3) COLLATE utf8_bin NOT NULL COMMENT '币种',
  `CREDIT_LIMIT` decimal(13,0) NOT NULL COMMENT '信用额度',
  `CURR_BAL` decimal(15,2) NOT NULL COMMENT '当前余额',
  `EMAIL` varchar(80) COLLATE utf8_bin DEFAULT NULL COMMENT '电子邮箱',
  `MOBILE_NO` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT '手机号码',
  `CREATED_DATETIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` timestamp NULL DEFAULT NULL COMMENT '最后修改时间',
	`BLOCK_CODE` varchar(27) COLLATE utf8_bin DEFAULT NULL COMMENT '账户锁定码',
  `LOCK_DATE` date DEFAULT NULL COMMENT '锁定日期',
  PRIMARY KEY (`ACCT_NO`,`ACCT_TYPE`),
  KEY `IDX_AMC_ACCOUNT_MODIFY_DATE` (`LAST_MODIFIED_DATETIME`),
  KEY `IDX_AMC_ACCOUNT_CUSTID` (`CUST_ID`),
  KEY `IDX_AMC_ACCOUNT_CARDNO_PRODUCTCD` (`DEFAULT_LOGICAL_CARD_NO`,`PRODUCT_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT '账户信息表';

CREATE TABLE `AMC_TRANSFER_TRACE` (
	`SYS_TRANS_ID` VARCHAR (32) COLLATE utf8_bin NOT NULL COMMENT '系统流水号',
	`CONSUMER_TRANS_ID` VARCHAR (32) COLLATE utf8_bin NOT NULL COMMENT '业务流水号',
	`TRANSFER_TYPE` VARCHAR (8) COLLATE utf8_bin DEFAULT NULL COMMENT '转账类型',
	`BIZ_DATE` date DEFAULT NULL COMMENT '业务日期',
	`ORG` CHAR (12) COLLATE utf8_bin DEFAULT NULL COMMENT '机构号',
	`PRODUCT_CD` CHAR (6) COLLATE utf8_bin DEFAULT NULL COMMENT '产品代码',
	`CARD_NO` VARCHAR (19) COLLATE utf8_bin DEFAULT NULL COMMENT '卡号',
	`ACCT_TYPE` CHAR (1) COLLATE utf8_bin DEFAULT NULL COMMENT '账户类型',
	`ACCT_NO` BIGINT (20) DEFAULT NULL COMMENT '账户编号',
	`TRANSFER_TIME` CHAR (14) COLLATE utf8_bin DEFAULT NULL COMMENT '转账请求时间',
	`TRANSFER_STATUS` VARCHAR (10) COLLATE utf8_bin DEFAULT NULL COMMENT '转账状态',
	`TRANSFER_DESC` VARCHAR (500) COLLATE utf8_bin DEFAULT NULL COMMENT '结果描述',
	`PAYER_ACCT` VARCHAR (32) COLLATE utf8_bin DEFAULT NULL COMMENT '付款人帐号',
	`PAYER_NAME` VARCHAR (120) COLLATE utf8_bin DEFAULT NULL COMMENT '付款人名称',
	`PAYER_BRNO` VARCHAR (14) COLLATE utf8_bin DEFAULT NULL COMMENT '付款人行号',
	`PAYER_BRNAME` VARCHAR (180) COLLATE utf8_bin DEFAULT NULL COMMENT '付款人行名称',
	`PAYEE_ACCT` VARCHAR (32) COLLATE utf8_bin DEFAULT NULL COMMENT '收款人帐号',
	`PAYEE_NAME` VARCHAR (120) COLLATE utf8_bin DEFAULT NULL COMMENT '收款人名称',
	`PAYEE_BRNO` VARCHAR (14) COLLATE utf8_bin DEFAULT NULL COMMENT '收款人行号',
	`PAYEE_BRNAME` VARCHAR (180) COLLATE utf8_bin DEFAULT NULL COMMENT '收款人行名称',
	`AMT` VARCHAR (20) COLLATE utf8_bin DEFAULT NULL COMMENT '金额',
	`FEE` VARCHAR (20) COLLATE utf8_bin DEFAULT NULL COMMENT '手续费',
	`B003` VARCHAR (6) COLLATE utf8_bin DEFAULT NULL COMMENT '交易处理码',
	`TRAN_DATE_TIME` VARCHAR (10) COLLATE utf8_bin DEFAULT NULL COMMENT '交易日期时间',
	`REF_NBR` VARCHAR (23) COLLATE utf8_bin DEFAULT NULL COMMENT '检索参考号',
	`TRAN_CURR_CODE` CHAR (3) COLLATE utf8_bin DEFAULT NULL COMMENT '交易币种代码',
	`POST_DATE` date DEFAULT NULL COMMENT '入账日期',
	`RTNCD` VARCHAR (10) COLLATE utf8_bin DEFAULT NULL COMMENT '银行返回码',
	`RTNINF` VARCHAR (300) COLLATE utf8_bin DEFAULT NULL COMMENT '银行返回码描述',
	`LAST_MODIFIED_DATETIME` datetime DEFAULT NULL COMMENT '时间戳',
	`PAY_ROUTE_CODE` VARCHAR (2) COLLATE utf8_bin DEFAULT NULL COMMENT '支付路由通路',
	`WORK_DATE` CHAR (8) COLLATE utf8_bin DEFAULT NULL COMMENT '银行工作日期',
	`RECON_CODE` VARCHAR (32) COLLATE utf8_bin DEFAULT NULL COMMENT '对账码',
	`TARGET_DCN` VARCHAR (10) COLLATE utf8_bin DEFAULT NULL COMMENT '目标DCN',
	PRIMARY KEY (
		`SYS_TRANS_ID`,
		`CONSUMER_TRANS_ID`
	),
	KEY `IDX_AMC_TRANSFER_TRACE_ACCT` (`ACCT_NO`, `ACCT_TYPE`) USING BTREE,
	KEY `IDX_AMC_TRANSFER_TRACE_CARD` (`CARD_NO`) USING BTREE,
	KEY `IDX_TRANSFER_TRACE_BZDT` (`BIZ_DATE`)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin COMMENT '转账流水表';

CREATE TABLE `AMC_REQ_HST` (
  `SYS_TRANS_ID` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '系统流水号',
	`CONSUMER_TRANS_ID` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '业务流水号',
  `CHANNEL_ID` varchar(4) COLLATE utf8_bin DEFAULT NULL COMMENT '请求渠道',
  `CARD_NO` varchar(19) COLLATE utf8_bin DEFAULT NULL COMMENT '卡号',
  `B003` varchar(6) COLLATE utf8_bin DEFAULT NULL COMMENT '交易处理码',
  `REF_NBR` varchar(23) COLLATE utf8_bin DEFAULT NULL COMMENT '检索参考号',
  `B039` char(2) COLLATE utf8_bin DEFAULT NULL COMMENT '交易结果码',
  `RESP_DESC` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '返回描述',
  `ORIG_DATA` varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '原数据',
  `MSG_CONTENT` varchar(1580) COLLATE utf8_bin DEFAULT NULL COMMENT '报文内容',
  `CREATED_DATETIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_MODIFIED_DATETIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最后更新时间',
  PRIMARY KEY (`CONSUMER_TRANS_ID`,`SYS_TRANS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT '交易报文日志表';

CREATE TABLE `AMC_SYSTEM_STATUS` (
  `STATUS_ID` int(11) NOT NULL COMMENT 'STATUS_ID',
  `BUSINESS_DATE` date NOT NULL COMMENT '系统联机服务日期',
  `PROCESS_DATE` date NOT NULL COMMENT '批量处理日期',
  `LAST_PROCESS_DATE` date NOT NULL COMMENT '上一批量日期',
  `GRACE_TIME` datetime DEFAULT NULL COMMENT 'GRACE_TIME',
  `MTN_DATE` datetime NOT NULL COMMENT '上次维护日期',
  `JPA_VERSION` int(11) NOT NULL COMMENT 'JPA_VERSION',
  `AUTO_FLAG` varchar(1) COLLATE utf8_bin DEFAULT '0' COMMENT '自动日切标识',
  PRIMARY KEY (`STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='系统状态表';

CREATE TABLE `AMC_TABLE_SEQ` (
  `TABLE_NAME` varchar(20) COLLATE utf8_bin NOT NULL COMMENT '表名',
  `SEQ_VAL` bigint(20) NOT NULL COMMENT '当前SeqNo',
  PRIMARY KEY (`TABLE_NAME`),
  UNIQUE KEY `TABLE_NAME` (`TABLE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='系统流水表';